### ISSUE TITLE
Gocompat doesn't reach objects in Go1.14.1

### ISSUE THREAD

**Issue by miguelpires** [smola/gocompat#14]
Hi. I noticed some unexpected behavior in gocompat with go1.14.1. Everything works as expected with go1.13.1, so the newer version seems to be triggering the issue.

Running `gocompat reach ./...` with go1.14.1 results in an empty response whereas the same produced a list of exported objects with go1.13.1

Running `gocompat save ./...` writes the paths to the packages but nothing else, similar to this:
```
{"Packages":[{"path":"x/y/z","objects":{}}],"Reachable":null}
```

**Comment by smola** [comment]
@MiguelPires Thanks for the report! I could reproduce this at some point, but not anymore in my latest build. You can try with master.

**Comment by miguelpires** [comment]
I can confirm it's working again. Thanks!
