### ISSUE TITLE
Example how to use in CI builds ?

### ISSUE THREAD

**Issue by gunnsth** [smola/gocompat#8]
Great project.  Would be nice to have an easy way to call this in builds and exit with code 1 if fails.

I guess it would involve comparing the current checkout with master (or a differently configured base branch) and return with exit code 1 if there was a failure with whatever compatibility options are set.

**Comment by smola** [comment]
@gunnsth You have two options. The exact parameters will depend on the CI service and what do you want to compare (e.g. PRs against master, master against latest stable tag...). In any case, `gocompat compare` exit code is 1 if there is any detected change.

### Option 1

```bash
git checkout master
gocompat save ./...
git checkout ${CURRENT_REF}
gocompat compare ./...
```

### Option 2

```
gocompat compare --git-refs=master..${CURRENT_REF} ./...
```
